// <auto-generated />
using System;
using ETicaret.Net8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETicaret.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240428110233_L")]
    partial class L
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ETicaret.Model.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "XM",
                            CategoryId = 4,
                            Description = "Tasarım Ön Gül Baskı Baggy Pantolon - Bej",
                            ISBN = "HG1133213",
                            ImageUrl = "1",
                            ListPrice = 699.99000000000001,
                            Price = 599.99000000000001,
                            Price100 = 450.99000000000001,
                            Price50 = 500.0,
                            Title = "Kumaş Baggy Pantolon"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Zhara",
                            CategoryId = 3,
                            Description = "Kuş Detaylı Sweatshirt - Beyaz",
                            ISBN = "SW35335334",
                            ImageUrl = "2",
                            ListPrice = 350.99000000000001,
                            Price = 325.99000000000001,
                            Price100 = 300.0,
                            Price50 = 310.99000000000001,
                            Title = "Sweatshirt - Beyaz"
                        },
                        new
                        {
                            Id = 3,
                            Author = "BHRR",
                            CategoryId = 6,
                            Description = "About Basic Sırt Nakışlı Kısa Kol Gömlek - İndigo",
                            ISBN = "HGGF35335334",
                            ImageUrl = "2",
                            ListPrice = 550.99000000000001,
                            Price = 425.99000000000001,
                            Price100 = 400.0,
                            Price50 = 410.99000000000001,
                            Title = "Sırt Nakışlı Kısa Kol Gömlek - İndigo"
                        });
                });

            modelBuilder.Entity("ETicaret.Net8.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Ayakkabı"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 12,
                            Name = "T-shirt"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            Name = "SweatShirt"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Pantolon"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Eşofman"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 15,
                            Name = "Gömlek"
                        });
                });

            modelBuilder.Entity("ETicaret.Model.Models.Product", b =>
                {
                    b.HasOne("ETicaret.Net8.Models.Category", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
